{% set name = "google-drive" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eduardogr/google-drive-python/archive/v{{ version }}.tar.gz
  sha256: 01c2fb8aec36185bf6efb617fb9c30861075f85b5b95c655a4e5bf52ffd933d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - google-drive = googledrive.cli:googledrive

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dataclasses ==0.6
    - google-api-python-client ==1.8.0
    - google-auth-httplib2 ==0.0.3
    - google-auth-oauthlib ==0.4.1
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - googledrive

about:
  home: https://github.com/eduardogr/google-drive-python
  summary: Library and cli to manage and interact with your Google Drive
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
